# Generated by Django 2.1.7 on 2019-10-09 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'Libraries'},
        ),
        migrations.AddField(
            model_name='method',
            name='long_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='method',
            name='parent_library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Library'),
        ),
        migrations.AddField(
            model_name='method',
            name='short_description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
