# Generated by Django 2.1.7 on 2019-10-09 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191009_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='parent_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Language'),
        ),
    ]
