# Generated by Django 2.1.7 on 2019-10-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_method_parent_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='use_example',
            field=models.CharField(default='', max_length=200),
        ),
    ]
